### ISSUE TITLE
[QUESTION] Extension for VS Community 2017?

### ISSUE THREAD

**Issue by mo-mueller** [kevinkyang/auto-comment-blocks#1]
Hi,

I'm looking for exactly this extension but for VS Community 2017 and I have not found anything like this yet. Could you make this extension for VS Community 2017, too?

**EDIT:**

I have just noticed that is already possible i you write "/**" above a function. But if you write that on a random place in your code it is not working. And that would be nice, too.

**Comment by kevinkyang** [comment]
Unfortunately Visual Studio's extension API is completely different from VS Code, so I can't help on that front. There may be other comment extensions for Visual Studio that are similar where you can contact the author and ask for expanded functionality.
