### ISSUE TITLE
Support Qt-style documentation comments

### ISSUE THREAD

**Issue by markasoftware** [kevinkyang/auto-comment-blocks#2]
Qt-style comments use /*! instead of /**, usually. For example, like this:

```
/*!
 * this is documentation
 * very documentation, much help
 */
```

**Comment by kevinkyang** [comment]
I assume you only need this for C++? I think it can be done. I'll work on it tomorrow.

**Comment by markasoftware** [comment]
Also C. Thanks!

**Comment by kevinkyang** [comment]
Alright, just updated the extension to support QDoc comments for C/C++. Please give it a whirl and report back if there are any issues.

**Comment by markasoftware** [comment]
Working well. Thanks!
