### ISSUE TITLE
Support for .php

### ISSUE THREAD

**Issue by Nektro** [kevinkyang/auto-comment-blocks#4]
VS Code doesn't autocomplete block comments by default so PHP would be super handy

**Comment by kevinkyang** [comment]
My current implementation is not working in PHP for some reason. It works in every other language, so I wonder if PHP has a separate code engine or something. I'll have to look into it, but it's not possible for now.

**Comment by kevinkyang** [comment]
Actually, I figured this one out, it was my fault. Expect this to be added in the next update.

**Comment by kevinkyang** [comment]
The new update has PHP support. Please open a new issue if you find any new bugs.
