### ISSUE TITLE
Support for .js

### ISSUE THREAD

**Issue by Nektro** [kevinkyang/auto-comment-blocks#5]
VS Code doesn't autocomplete block comments by default so JavaScript support would be super handy

**Comment by kevinkyang** [comment]
JavaScript block comments are a default VS Code feature. Does it not work for you? In .js/.ts files, after typing `/**`, a completion item called `JSDoc comment` should appear, and it should work just like my extension afterwards.

**Comment by Nektro** [comment]
Hmm, when I first posted this, it didn't autocomplete and today it does. Sorry bout that
