### ISSUE TITLE
Support for // and ///

### ISSUE THREAD

**Issue by rianquinn** [kevinkyang/auto-comment-blocks#7]
Please provide support for both // and /// style C++ comment blocks.

**Comment by kevinkyang** [comment]
If you only want a single-line comment, this would insert a new `//` or `///` every time you press enter, though. Thoughts?

**Comment by rianquinn** [comment]
Other plugins that I have used for Sublime Text have you hit shift+enter to break the comment block. They also preserve indentation. So for example:

```
/// Blah blah blah
/// - I type a bunch of text and hit enter
/// - the next like starts with a "/// " to preserve indentation
```

**Comment by rianquinn** [comment]
This is SUPER helpful for writing long winded doxygen comments / documentation

**Comment by kevinkyang** [comment]
Interesting. If the shift+enter method is possible in VSCode then I'll add this feature.

**Comment by rianquinn** [comment]
Awesome!!!

**Comment by kevinkyang** [comment]
Okay, the 0.3.0 update now has this feature. It's disabled by default so normal users are unaffected, so you'll have to enable it in the settings. Could you use it and open a new issue if there are bugs/incorrect functionality? I don't use this style of comment so there are probably use cases that I am not covering.

**Comment by rianquinn** [comment]
seems to work great. Thanks a ton

**Comment by callodacity** [comment]
Could we get this to work in other languages that also support `//` style comments?
e.g. JavaScript has the same style comments, and this would be great to use in that language too.

Other languages that also support `//` style comments:

* Sass (scss)
* Less
* C#
* Obj-C (Obj-C++)

**Comment by kevinkyang** [comment]
@callodacity Sorry for the late response. I'm actually working on this right now for (almost) all single-line comment types (`//`, `#`, `;`):  see #8. But I'm thinking about reversing how it works, so `shift+enter` inserts a new comment line, while `enter` behaves as usual. I prefer this for several reasons but I wonder if anyone has a problem with it.

**Comment by callodacity** [comment]
No worries!  
I think maybe making that configurable would be the best way to accommodate for everyone. Sublime Text will always continue, unless you press <kbd>Shift / Cmd</kbd> + <kbd>enter</kbd>. I'm sure there are subtle differences in other editors, too.
