### ISSUE TITLE
Support for `#` and `;`?

### ISSUE THREAD

**Issue by Qwerp-Derp** [kevinkyang/auto-comment-blocks#8]
`#` is used in many languages for comments, e.g. Python, Ruby and Crystal (which is what I'm using now). It'd be great to have auto-commenting for these languages.

Also, `;` is used in Lisp dialects (e.g. Common Lisp, Clojure) as comments.

**Comment by kevinkyang** [comment]
I think it's definitely possible. Would you mind checking the [list of officially supported languages](https://code.visualstudio.com/docs/languages/identifiers) and tell me which languages use `#` and `;`? For languages that are not officially supported, I'm thinking of just making a setting where you can specify languageIds to enable the feature for.

**Comment by kevinkyang** [comment]
Finally got this done. 1.0 update now supports this for most officially supported languages. For a language like Crystal that is not officially supported, there's a setting where you can add `languageId`s to enable it for those languages. You'll have to search the language extension for its `languageId` though (probably just `crystal` in this case).
