### ISSUE TITLE
Multiline support for rust?

### ISSUE THREAD

**Issue by pckilgore** [kevinkyang/auto-comment-blocks#9]
Before I fiddle around / maybe submit a PR for `/** */` style rust comments, I just want to make sure there wasn't a reason it wasn't already implemented (given the rust single line style is).

Thanks!

**Comment by kevinkyang** [comment]
No reason, I just overlooked it, there may be others missing too. Feel free to submit a PR or I can do it tomorrow when I'm free. It's pretty straightforward.

**Comment by kevb34ns** [comment]
63c5d9ffda731c7b7885bd15ae469413dc21b6d7
